### ISSUE TITLE
WinRM command doesn't terminate

### ISSUE THREAD

**Issue by ghost** [test-kitchen/winrm-transport#3] opened 2015-04-26 22:45 UTC
I've observed this behavior when trying to install VirtualBox on a Windows Server 2012 R2 VM.
Using: test-kitchen 1.4.0.rc.1, kitchen-vagrant 1.7.0.rc.1, winrm-transport 1.0.0

The WinRM session seems to be stuck in "running" mode even though the installation had successfully completed. It calls WinRMWebService::send_message() and never gets a response. Feels like the guest end of the connection had disconnected without informing the host.

Ultimately the session times out, and calling "kitchen converge" right afterwards succeeds. 

This is my recipe:

``` ruby
include_recipe 'chocolatey'
chocolatey 'virtualbox' do
  version '4.3.26'
end
```

(Note that the same thing happened when using the VirtualBox cookbook so it's not related to chocolatey)

Thanks,
-Omer

**Comment by tyler-ball** [comment] 2015-05-11 21:12
Hey @ozenhaman - can you try this again with the latest ChefDK?  It includes some updated versions of the dependencies you are using.

If you can reproduce this could you try running test kitchen with `-l debug` to set the logging to debug level?  Then paste the contents of your `.kitchen/logs/*` files into a gist so we can see what is happening.

**Comment by tyler-ball** [comment] 2015-06-03 20:32
I'm going to go ahead and close this since there hasn't been a response - re-open this if you're still having issues in the latest ChefDK!

**Closed as completed** 2015-06-03 20:32 UTC
Labels: Feedback Requested
